name: Example workflow for dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Change to the project directory
        run: cd ../
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        #with:
        #  args: --directory=WebGoat.NET
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
