name: Example workflow for dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@3.0.3
      - name: List files
        run: ls
      - name: Restore dependencies
        run: dotnet restore WebGoat.Net.sln
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
