name: Example workflow for dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: List project directory
        run: ls 
      - name: Change to the project directory
        run: cd WebGoat
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        with:
          args: --directory=WebGoat
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
